version: '3'

services:
  dtls-client:
    build:
      context: cli
    container_name: cli
    entrypoint: /root/cli/init.sh
    networks:
      - private
    volumes:
      - ./cli:/root/cli
      - ./mbedtls:/root/mbedtls
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true

  nat-box:
    build:
      context: nat
    container_name: nat
    entrypoint: /root/nat/init.sh
    networks:
      - private
      - public
    volumes:
      - ./nat:/root/nat
      - ./mbedtls:/root/mbedtls
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  dtls-server:
    build:
      context: srv
    container_name: srv
    entrypoint: /root/srv/init.sh
    networks:
      - public
    volumes:
      - ./srv:/root/srv
      - ./mbedtls:/root/mbedtls
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true

networks:
  private:
  public:

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
